development:
  adapter: mysql2
  encoding: utf8
  database: justforim_development
  username: root
  password: root
  pool: 5
  timeout: 5000
  reconnect: true

test:
  adapter: mysql2
  encoding: utf8
  database: justforim_test
  username: root
  password: root
  pool: 5
  timeout: 5000
  
production:
  adapter: mysql2
  encoding: utf8
  database: justforim_production
  username: root
  password: root
  pool: 5
  timeout: 5000
  reconnect: true